### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by kei-sukey** [kei-sukey/furima-32584#14]
## 自身のフリマアプリのURL
https://furima-32584.herokuapp.com/

## Basic認証のIDとパスワード
ID: admin
パスワード: 1357

## 出品者用のメールアドレスとパスワード
ニックネーム: furima太郎
メールアドレス: abcde@sample.com
パスワード: abc123

## 購入者用のメールアドレスとパスワード
ニックネーム: フリマ花子
メールアドレス: sample@abcde.com
パスワード: 123abc

## 購入用カードの番号・期限・セキュリティコード
カード番号: 4242424242424242
有効期限: 12/25
セキュリティコード: 123

**Comment by mo1015** [comment]
ご提出ありがとうございます！
挙動確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます:tada:
おめでとうございます！
**※確認したのは必須機能のみで追加実装した機能については確認していません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるかご自身で再度確認をお願いいたします。**
